spring:
  datasource:
    url : jdbc:mysql://localhost:3306/pollapplication
    username : root
    password : Shivam@123
  jpa:
    show-sql : true  
    format-sql : true
    hibernate:
      ddl-auto : update 
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
